### ISSUE TITLE
Socket address already bound

### ISSUE THREAD

**Issue by rwynn** [dmulholland/ironclad#1]
Cool project.  Is there an actual error happening here?  Or just that the server RPC server is already bound?  Can that be detected to avoid this error?

$ ironclad export
Password: ***

**Error: listen tcp 127.0.0.1:54313: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted..**
[
  {
    ...
  }
]

**Comment by dmulholl** [comment]
I suspect it's just bad luck. I hardcoded an arbitrary port number for convenience when I was developing the application and it sounds like something is already using it on your system.

I'll fix this over the weekend by getting it to pick a random unused port. In the meantime you can specify a port number for it to use manually using the `config` command:

    $ ironclad config port 12345

Valid port numbers run from 1025 to 65535. Thanks for the heads up!

**Comment by rwynn** [comment]
I configured the port to various values.  Each time I configure the port the first command after that does not produce an error.  But if I then repeat the command, e.g. export, I do see the error.  Maybe this is just because the port is held by ironclad after each command for a period of time on purpose.  Thanks for looking into it.

**Comment by dmulholl** [comment]
That's trickier then. I think I've spotted the issue and 0.18.1 will hopefully fix it. I haven't packaged it as a release yet but you can 

    go get github.com/dmulholland/ironclad/ironclad

to update to it. 

A question I should have asked earlier - when you ran the second command, e.g. `export`, did the command print an error message but still work as expected?

**Comment by rwynn** [comment]
yes, printed an error message but still worked as expected.  I suspect it just needs to detect if it has already been done to avoid the message.

**Comment by rwynn** [comment]
@dmulholland, I tried version 0.18.1 but still getting the error message printed.  The message goes aways if I 

`
ironclad config timeout 0
`

So I think it's getting printed as a result of 

https://github.com/dmulholland/ironclad/blob/master/ironclad/cmd-cache.go#L72

**Comment by dmulholl** [comment]
0.19.0 which I've just pushed will hopefully fix this issue definitively. If you're still getting errors, let me know.

Thanks for the feedback so far, it's been really helpful.

**Comment by rwynn** [comment]
not seeing the issue with the latest code.  thank you.

**Comment by dmulholl** [comment]
That's great, thanks for reporting the issue.
