### ISSUE TITLE
Add ability to disable editor for notes on ironclad add

### ISSUE THREAD

**Issue by rwynn** [dmulholland/ironclad#2]
Hi,
I decided to learn React by building a desktop UI for Ironclad - https://github.com/rwynn/llave.  It works pretty well but I was not able to integrate the notes feature easily since it forces an editor to open to enter the notes.  Would it be possible to add a switch to the add command to allow entering the notes without opening a text editor? Thanks.

**Comment by dmulholl** [comment]
Hi Ryan, interesting project - definitely looking forward to seeing it in action.

I can certainly add a flag - say `--no-editor` - to the `add` command to avoid launching an external editor and instead just read the notes string directly from standard input. Would that work for you?

We might have to do something similar with the `edit` command too.

**Comment by rwynn** [comment]
Yes, that would work. Good catch, I would need the flag on the edit command too.

**Comment by dmulholl** [comment]
No bother, I'll try to push an update today or tomorrow.

**Comment by dmulholl** [comment]
I just pushed an update 0.20.0.dev which adds a `--no-editor` flag for the `add` and `edit` commands.

**Comment by rwynn** [comment]
That update works perfectly and I am now able to simply pass the notes on standard in.  Thanks for the quick response!

**Comment by rwynn** [comment]
Hi Darren,
Would you be able to make an official release with this enhancement when you have some time?

**Comment by dmulholl** [comment]
I've just released the update as 0.20.0. Good luck with the project!

**Comment by rwynn** [comment]
@dmulholland thought you might find this interesting.  I've added web and mobile support to llave using the web crypto API.  this makes it possible to read an ironclad database on a mobile device.  Encrypt/Decrypt is implemented but I've only put Decrypt into the UI at the moment.  https://github.com/rwynn/llave

**Comment by dmulholl** [comment]
That looks fantastic - the interface is really elegant! 

I'm surprised you were able to build it on top of the command-line binary as I hadn't thought about using it in that way at all when I was writing it. I've never used Electron or Cordova myself - I must check them out when I get a chance.

I'll add a link to llave to the release notes for people to check out.

**Comment by rwynn** [comment]
Thanks for taking a look.  I really liked the simple approach your took in your utility and wanted to expand the ways I could use it - mobile specifically.

Unfortunately, I cannot think of a way to ensure web crypto is totally safe - problem being resource integrity.  But I've tried to mitigate the problem with content security policies, subresource integrity, etc.

I wish there was a way to encode the SHA signature of the root resource in the URL and have the browser validate that.  But until that browser feature exists, I think a user signed native mobile application is the safest alternative.
