### ISSUE TITLE
Win7: init command error

### ISSUE THREAD

**Issue by cpkio** [dmulholland/ironclad#3]
`> ironclad init file.pwd`
Master Password: Error: The specified program requires a newer version of Windows.

**Comment by dmulholl** [comment]
I haven't seen that before. I wonder, are you using one of the pre-built binaries on a 32-bit system? The pre-built binaries are all 64-bit - this could be the error Windows throws if you try to run a 64-bit binary on a 32-bit system.

**Comment by cpkio** [comment]
I used pre-built binaries for x64 on Win10 & Win7 systems with the same result. I tried to investigate, but due to limited time with no luck. Probably will try to compile by myself and see what happens.

**Comment by dmulholl** [comment]
That's very strange. I don't have access to a Windows system to test on at the moment unfortunately, but I will when I get the chance. In the meantime if you figure out what's going on, please do let me know.

If you want to try compiling for yourself you can download the Go compiler from here:

https://golang.org/dl/

Once you have the compiler installed you should be able to download and install the latest version of Ironclad by running the following command:

    go get github.com/dmulholland/ironclad/ironclad

Thanks for letting me know about the issue.

**Comment by cpkio** [comment]
Well, the binary I got with `go get` command (at Win10x64) is working fine (file size 9 751 040). Want me to share it?
