### ISSUE TITLE
[Feature Request] 2FA - Authenticator additoin

### ISSUE THREAD

**Issue by themotu** [dmulholland/ironclad#5]
Many websites offer 2FA with auth codes. Would be a cool addition to support this and after a single paste of the password also copy the Gauth for 30 seconds to paste during the period.

**Comment by dmulholl** [comment]
This is an interesting idea. I hadn’t thought of it but adding it now would break backwards compatibility with the database format. If we make it to version 2 I’ll definitely consider adding it.
