### ISSUE TITLE
No obvious way to change the master password

### ISSUE THREAD

**Issue by sturmf** [dmulholland/ironclad#6]
I don't know if I am missing something, but there does not seem to be a way to change the master password?

**Comment by dmulholl** [comment]
You're right, I never got around to implementing a command to change the master password. I'll do that for the next point release.

It's an ugly workaround, but in the meantime you can initialise a new database using the new password, export the entries from the old database, then import them into the new one.

**Comment by dmulholl** [comment]
Just released version 1.1.0 with a new `setpass` command for setting a new master password. Thanks for the feedback.
