### ISSUE TITLE
Issues in Add command

### ISSUE THREAD

**Issue by Suleman-Elahi** [dmulholland/ironclad#7]
![image](https://user-images.githubusercontent.com/24384996/39108331-4bd7db86-46e5-11e8-88d0-1d2f59aa6fdc.png)

After running the add command, there is nothing happening. I am typing the value from "Title" but it doesn't show up. Looks like it hangs there !!!!

~ Using it on Windows 10, build 16299.371

**Comment by dmulholl** [comment]
Sorry, I never had convenient access to a Windows machine to investigate this properly. I'll close this for now as there have been quite a few updates since, but feel free to reopen the issue if the problem persists.
